### PR TITLE
Add RPM based distro support to claudia_launcher

### PR DESCRIPTION
**Pull request by dsonck92**
Provides the ability to use the built in application database on RPM based distributions like OpenSUSE and Fedora.

Has been tested on OpenSUSE Leap 42.1 and OpenSUSE Tumbleweed

### CODE REVIEW

**Comment by simonvanderveldt** [comment]
This relates to #136
Seems like just checking if the executable exists would be good enough and that would work for ever distro.

**Comment by richardhenwood** [comment]
@net147 : I've tested this patch, and it works. Can it be merged please?

**Comment by richardhenwood** [comment]
A further comment: I am not sure this patch is perfect, but I think it is an improvement and will allow further work on fedora.

**Comment by richardhenwood** [comment]
@falkTX  : can you give this PR some attention.

**Comment by net147** [comment]
@richardhenwood I am a contributor not a maintainer.

**Comment by richardhenwood** [comment]
ping @falkTX

**Pull request merged**
