### PR TITLE
Patchcanvas improvements

### PR DESCRIPTION
**Pull request by nick87720z**
There are many changes, whose describtions may be found in extended description for each change.
For summary:
- Fixed antialiasing problem, caused by fact, that when line coordinates are specified by integer, they are still positioned in subpixel way, thus point 4,4 means 4.0,4.0 and while has size 1, it is blurred into 2x2 square. Using floating point where is necessary fixes that. To achieve that line borders are drawen inside of visible box contour as part of contents.
- More improvements in all look:
  - rounded corners for boxes or square ports (for ports - only internal corners)
  - box and port text is centered
  - group text is aligned vertically with icon. If icon is not enabled, text has static gap between self and top group side
  - font-aware automatic port height (port_height theme parameter is replaced with port_text_padding)
  - Mouse-hover visual feedback
  - Ability to remove connections by clicking on them with middle mouse button. For correct mouse reaction spline connections are drawen with stroker class, thus line itself is represented as valid fillable area, capable for correct mouse reaction.
  - Linear connections are drawen with rounded caps, since sometimes they are rendered on top of boxes. For spline connections caps are changed from square to flat, thus not covering ports anymore.
Themes improvements:
  - Modern Tiny is now yet compact - ports of single type are without gaps between, only 1 pixel between port groups of different types
  - better colors for Modern Light - slightly grey background, contrast port border
  - All modern themes now have box/port outlines set as cosmetic - i.e., their visible thickness doesn't depend on scale
  - OOStudio theme: ports are slightly out of gorup box by 1pix - close to reall hardware look in some cases
  - Added new theme: Neoclassic (aka in latest patchage)

upd: Some unmentioned changes:
- Box coordinates are rounded to integers after each move, since subpixel positioning relies on that (just adds 0.5 where is necessary).
- In themes: hsv model is used in some places -more humand-friendly, that RGB

### CODE REVIEW

**Comment by nick87720z** [comment]
There are some more improvements, which i have as questions:
- line-styled connections may be created as splines with very tiny static curve parts for caps (thus, almost all look is linear, only about 6 - 10 pixels near of caps are curved, thus "linear" connection is rather "dense cord").
- Appart of middle-click disconnection, more variants coud be possible:
  - Middle click on port/box to remove all its connections
  - Erasing connection lines by simple hover, while holding some key combination or toggling some hotkey.
  - Selecting multiple lines, then pressing Delete
  - For port/box selection may be special disconnect keybinding, while Del is reserved for more obvious things (in claudia - client termination).

**Comment by falkTX** [comment]
The more commits you add, the harder it will be for me to merge them...
It's better to target these canvas changes to carla anyway, please try to do that instead of keep updating the cadence one.

**Comment by nick87720z** [comment]
I noticed patchcanvas implementation in c++ dir... are you going to use same patchcanvas implementation for both cadence and carla?
This canvas could go in separate lib - qpatchcanvas (since it is qt-based).
Changes above are targeted for catia/claudia

**Comment by falkTX** [comment]
The c++ implementation is abandoned.
Cadence and Carla use exactly the same python files, in exactly the same way, but Carla's one has evolved a little and has more features. That's why I mentioned in IRC before that these changes should target Carla's patchbay.
I will merge it back to Cadence code later on.
I have no interest on making this a generic library.

**Comment by falkTX** [comment]
As mentioned before, I will merge the carla changes at a later point.
There are some regressions in there, so not going to do that yet. Perhaps when Carla 2.1 gets out

**Pull request closed without merging**
