### PR TITLE
fix linux alsa card detection in jacksettings

### PR DESCRIPTION
**Pull request by RushOnline**
Wrong card/device detection under linux. I've rewrite JackSettingsW.getAlsaDeviceList to get more reliable information and split capture/playback device detection.

### CODE REVIEW

**Comment by RushOnline** [comment]
Example JackSettingsW.getAlsaDeviceList returns on my computer:

```python
# return of JackSettingsW.getAlsaDeviceList()
['hw:0,2 [VT2020 Alt Analog]', 'hw:0,0 [VT2020 Analog]']

# return of JackSettingsW.getAlsaDeviceList('CAPTURE')
['hw:0,2 [VT2020 Alt Analog]', 'hw:1,0 [USB Audio]', 'hw:0,0 [VT2020 Analog]']

# return of JackSettingsW.getAlsaDeviceList('PLAYBACK')
['hw:0,1 [VT2020 Digital]',
 'hw:0,3 [HDMI 0]',
 'hw:0,2 [VT2020 Alt Analog]',
 'hw:0,0 [VT2020 Analog]']
```

**Comment by falkTX** [comment]
Thanks for the patch.

I don't like seeing the numbers though (as in "hw:0,1"), those should be hidden from the user;
it's less confusing that way.

I'll review the patch sometime soon.

**Comment by RushOnline** [comment]
I've just left your return conventions intact. For user we can display only device name (VT2020 Analog/VT2020 Digital/USB Audio/HDMI 0/etc). But I'm affraid we can meet name collisions with this way (2 usb audio for example).

**Comment by falkTX** [comment]
the device names ("ids") are supposed to be unique.
if not then something needs to change in ALSA.

we can't use numbers for audio devices, those are not reliable.

**Comment by RushOnline** [comment]
Device id is unique across the card. So if we want to show descriptive names to user, we must use `"<card-id> <device-id>"`, r u agree?

Example card configuration:

```bash
$ cat /proc/asound/cards
 0 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xf7d10000 irq 46
 1 [U0x46d0x8d9    ]: USB-Audio - USB Device 0x46d:0x8d9
                      USB Device 0x46d:0x8d9 at usb-0000:00:14.0-2, full speed
 2 [U0x46d0x8d9    ]: USB-Audio - USB Device 0x46d:0x8d9
                      USB Device 0x46d:0x8d9 at usb-0000:00:14.0-3, full speed
```

What distinguish name we must show to user for USB-Audio cards in this case? If we will do complex logic, the best what we can do is showing `[ PCH, USB-Audio-1, USB-Audio-2 ]`.

But user can ask:
1. What is PCH ?!
2. Where is USB-Audio-1 and where is USB-Audio-2 ?!

So, we must stop somewhere to make software more and more user-friendly or we will loose flexibility. I can rewrite JackSettingsW.getAlsaDeviceList function to grab as many details as it is possible, after that you will implement it in UI as you want. It's ok?

**Comment by falkTX** [comment]
The "old" method I have in place is already verbose enough, no?
Stuff like:
```
hw:Intel,0 [92HD75B2X5 Analog]
hw:Intel,3 [HDMI 0]
```
The first string is the card/device id, then between brackets is the name given by alsa.
This format will remain as-is.

The way alsa devices are probed/requested is what can change.

**Comment by RushOnline** [comment]
1. "old" method doesn't detect record devices at all.
2. I have two USB sound cards at home (two Rocksmith cables). At the
evening I'll give you complete information about what ALSA reports in this
case.

2015-01-14 12:22 GMT+03:00 Filipe Coelho <notifications@github.com>:

> The "old" method I have in place is already verbose enough, no?
> Stuff like:
>
> hw:Intel,0 [92HD75B2X5 Analog]
> hw:Intel,3 [HDMI 0]
>
> The first string is the card/device id, then between brackets is the name
> given by alsa.
> This format will remain as-is.
>
> The way alsa devices are probed/requested is what can change.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/falkTX/Cadence/pull/93#issuecomment-69889229>.
>



-- 
Cogito ergo sum

**Comment by falkTX** [comment]
I'm not speaking of the "old" method of dectecting devices, but the "old" method of showing them in Cadence.
ie, this syntax:
```
hw:DEVICE-ID,SUBDEVICE-NUMBER [DEVICE-NAME]
```
has to remain, but the way the cards are detected can change.

**Comment by RushOnline** [comment]
ALSA operates triplets: `CARD DEVICE SUBDEVICE`. I never see `SUBDEVICE` different than zero, but it exists in ALSA config. So, seems like you means:

```
hw:CARD-NAME,DEVICE-NUMBER [DEVICE-NAME]
```

Where card name can be taken from `/proc/asound/cards` and `DEVICE-NUMBER` from `device: NUMBER` line in `cat /proc/asound/card*/pcm*/info `:

```bash
$ cat /proc/asound/card1/pcm0c/info 
card: 1
device: 0
subdevice: 0
stream: CAPTURE
id: USB Audio
name: USB Audio
subname: subdevice #0
class: 0
subclass: 0
subdevices_count: 1
subdevices_avail: 1
```

With this:

```
$ cat /proc/asound/cards
 0 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xf7d10000 irq 46
 1 [U0x46d0x8d9    ]: USB-Audio - USB Device 0x46d:0x8d9
                      USB Device 0x46d:0x8d9 at usb-0000:00:14.0-2, full speed
``

It will take form ``hw:U0x46d0x8d9,0 [USB Audio]. Is it ok?

**Comment by falkTX** [comment]
probably, I'd have to do some tests locally to ensure the returned data is not less then the one "aplay -l" does.

**Comment by RushOnline** [comment]
My laptop sound cards configuration: http://pastebin.com/ARtesSwm

**Comment by RushOnline** [comment]
I'll rewrite it.

**Pull request closed without merging**
